src/main/java/br/com/kernel/negocio/pesoaltura_cpf/model/PesoAltura_CPF.java
package br.com.kernel.negocio.pesoaltura_cpf.model;

import java.io.Serializable;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import br.com.kernel.negocio.usuario.model.Usuario;

@Entity
@Table(name = "TBL_PES_ALT_CPF")
@SequenceGenerator(name = "SEQ_PES_ALT_CPF", sequenceName = "SEQ_PES_ALT_CPF")
public class PesoAltura_CPF implements Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	@EmbeddedId
	private CPFId cpfId;
	
	@ManyToOne
	@JoinColumn(name = "CPF", referencedColumnName = "CPF", nullable = false, updatable = false, insertable = false)
	private Usuario usuario;
	
	@Column(name = "PESO", nullable = false)
	private double peso;
	@Column(name = "ALTURA", nullable = false)
	private double altura;
	@Column(name = "DATA_REGISTRO")
	@Temporal(TemporalType.DATE)
	private Date dataRegistro;
	
			
	public PesoAltura_CPF(CPFId cpfId, Usuario usuario, double peso, double altura, Date dataRegistro) {
		super();
		this.cpfId = cpfId;
		this.usuario = usuario;
		this.peso = peso;
		this.altura = altura;
		this.dataRegistro = dataRegistro;
	}

	public PesoAltura_CPF() {
		super();
		// TODO Auto-generated constructor stub
	}

	public CPFId getCpfId() {
		return cpfId;
	}

	public void setCpfId(CPFId cpfId) {
		this.cpfId = cpfId;
	}

	public Usuario getUsuario() {
		return usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

	public double getPeso() {
		return peso;
	}

	public void setPeso(double peso) {
		this.peso = peso;
	}

	public double getAltura() {
		return altura;
	}

	public void setAltura(double altura) {
		this.altura = altura;
	}

	public Date getDataRegistro() {
		return dataRegistro;
	}

	public void setDataRegistro(Date dataRegistro) {
		this.dataRegistro = dataRegistro;
	}

	public double getImc() {
		return (this.peso / (altura * altura));
	}

}

WebContent/cadastroPaciente.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:p="http://primefaces.org/ui"
	xmlns:f="http://java.sun.com/jsf/core">

<h:head>
	<link href="https://fonts.googleapis.com/css?family=Nunito"
		rel="stylesheet" />
	<link rel="stylesheet" href="css/custom.css" />
	<link href="#{request.contextPath}/css/primeface.css" rel="stylesheet"
		type="text/css" />
</h:head>
<h:body>
	<h:form>
		<p:growl id="msgs" showDetail="false" autoUpdate="true" />
		<div class="cadastro">
			<p:fieldset legend="Cadastro">

				<h:outputLabel value="Nome: " />
				<p:inputText value="#{usuarioMB.usuario.nome}" size="60"
					required="true" requiredMessage="Campo nome é obrigatório" />

				<h:panelGrid columns="4" style="margin-bottom:10px" cellpadding="5">

					<h:outputLabel value="CPF:" />
					<p:inputMask id="cpf" value="#{usuarioMB.usuario.cpf}"
						mask="999.999.999-99" size="12" required="true"
						requiredMessage="Campo CPF é obrigatorio" />

					<h:outputLabel value="Data Nascimento:    " />
					<p:calendar value="#{usuarioMB.usuario.dtNascimento}"
						id="dtNascimento" required="true"
						requiredMessage="Campo Data de Nascimento é obrigatorio" 
						pattern="dd-MM-yyyy" mask="true" />

					<h:outputText value="Senha: " />
					<p:password id="senha" required="true"
						validatorMessage="A senha deve conter no minimo 6 caracteres"
						requiredMessage="Campo Senha é obrigatorio"
						value="#{usuarioMB.usuario.senha}" feedback="true" size="12"
						minLenght="8" maxlength="16">
						<f:validateLength minimum="6"></f:validateLength>
					</p:password>

					<h:outputLabel value="Sexo: " />
					<p:selectOneRadio id="sexo" value="#{usuarioMB.usuario.sexo}">
						<f:selectItem itemLabel="Masculino" itemValue="M" />
						<f:selectItem itemLabel="Feminino" itemValue="F" />
					</p:selectOneRadio>



<!-- 					<h:outputLabel value="Peso: " />
					<p:inputMask value="#{pesoAltura_CPFMB.pesoAltura_CPF.peso}" mask="999.9"
						size="4" required="true"
						requiredMessage="Campo Peso é obrigatorio" />

					<h:outputLabel value="Altura: " />
					<p:inputMask value="#{pesoAltura_CPFMB.pesoAltura_CPF.altura}" mask="9.99"
						size="3" required="true"
						requiredMessage="Campo Altura obrigatorio" /> -->

				</h:panelGrid>

				<div class="btn-cad">
					<h:panelGrid columns="6" cellpadding="8">
						<p:commandButton value="Confirmar" update="@form"
							action="#{usuarioMB.salvarUsuario}"  />
						<p:commandButton update="@form"
							actionListener="#{usuarioMB.clear}" value="Cancelar"
							immediate="true" action="index" />
					</h:panelGrid>
									
					
				</div>
			</p:fieldset>
		</div>
	</h:form>
</h:body>
</html>

WebContent/header.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:p="http://primefaces.org/ui"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:ui="http://java.sun.com/jsf/facelets">


<h:head>
	<link href="https://fonts.googleapis.com/css?family=Nunito"
		rel="stylesheet" />
	<link rel="stylesheet" href="css/custom.css" />
	<link href="#{request.contextPath}/css/primeface.css" rel="stylesheet"
		type="text/css" />
</h:head>
<h:body>
	<p:menubar>
		<p:menuitem id="home" value="Home" url="homePaciente.xhtml"
			icon="ui-icon-home" />

		<p:submenu id="user" label="#{loginBean.nomeUsuarioExibicao}"
			icon="ui-icon-person">
			<p:menuitem value="Pesquisar" url="consultaPaciente.xhtml" />
			<p:menuitem value="Perfil" url="perfilPaciente.xhtml" />
			<p:menuitem value="Gráfico" url="grafico.xhtml" />
		</p:submenu>

	</p:menubar>

	<div class="btn-sair">
	<p:commandButton value="Sair" action="#{loginBean.logOut}" />
	</div>

</h:body>
</html>

WebContent/homePaciente.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:p="http://primefaces.org/ui"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:ui="http://java.sun.com/jsf/facelets">

<h:head>
	<link href="https://fonts.googleapis.com/css?family=Nunito"
		rel="stylesheet" />
	<link rel="stylesheet" href="css/custom.css" />
	<link href="#{request.contextPath}/css/primeface.css" rel="stylesheet"
		type="text/css" />
</h:head>
<h:body>

	<div class="home">
	
		<h:panelGrid>
			<h:outputLabel value="Peso: " />
				<p:inputMask value="#{pesoAltura_CPFMB.pesoAltura_CPF.peso}" mask="999.9"
						size="4" />

					<h:outputLabel value="Altura: " />
					<p:inputMask value="#{pesoAltura_CPFMB.pesoAltura_CPF.altura}" mask="9.99"
						size="3" />
					<h:outputLabel value="CPF"/>
					<p:inputMask value="#{pesoAltura_CPFMB.pesoAltura_CPF.cpfId}" mask="999.999.999-99" />
					</h:panelGrid>
					
					<h:panelGrid columns="6" cellpadding="8">
						<p:commandButton value="Confirmar" 
							action="#{pesoAltura_CPFMB.salvar}"  />
		</h:panelGrid>
	
		<h:form>
			<p:growl id="msgs" showDetail="false" autoUpdate="true" />
			<p:fieldset legend="Dados">
				<h:panelGrid columns="8" cellpadding="7">
			CPF:<h:outputText value="#{loginUsuario.usuarioSessao.cpf}"/>
			Nome:<h:outputText value="#{loginUsuario.usuarioSessao.nome}"/>
        	Peso:<h:outputText value="#{loginBean.usuarioSessao.peso} kg" /> 
        	Altura:<h:outputText
						value="#{loginBean.usuarioSessao.altura} m" />
        	IMC:<h:outputText value="#{loginBean.usuarioSessao.imc}">
						<f:convertNumber maxFractionDigits="2" />
					</h:outputText>

				</h:panelGrid>
			</p:fieldset>
		</h:form>
</div>
	<div class="chart">
		<h:panelGrid columns="2" columnClasses="left,right" style="width:100%">
    		<p:chart type="line" model="#{chartView.animatedModel1}" style="width:400px;" />
		</h:panelGrid>
	</div>
</h:body>
</html>

WebContent/index.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:p="http://primefaces.org/ui">

<h:head>
	<link rel="stylesheet" href="css/style-login.css" />
	<link rel="stylesheet" href="css/custom.css" />
	<link href="https://fonts.googleapis.com/css?family=Nunito"
		rel="stylesheet" />
</h:head>
<h:body>
<div class="fundo">
	<h:form>
		<p:growl id="msgs" showDetail="false" autoUpdate="true" />
		<div class="form-login">
			<div class="user"></div>

			<h:panelGrid columns="2" position="center">
				<p:inputMask id="cpf" mask="999.999.999-99" placeholder="CPF"
					value="#{loginUsuario.cpf}" required="true"
					requiredMessage="Informe o CPF!" />
				<p:password id="nonFeedback" value="#{loginUsuario.senha}"
					placeholder="Senha" required="true"
					requiredMessage="Informe a senha!" />
			</h:panelGrid>
			
			<h:commandButton name="lastname" value="Login"
				action="#{loginUsuario.logar}" />

			<div class="register">
				<a href="cadastroPaciente.xhtml">Registre-se aqui.</a>
			</div>
		</div>
	</h:form>
	</div>
</h:body>
</html>